name: Release

on:
  workflow_dispatch:
  push:
    tags: 
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test
      run: go test -v

    - name: Build
      run: go build -v cmd/main.go

    - name: Rename artifcat
      run: mv main gver

    - name: Upload version file as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: gver-linux
        path: gver
        if-no-files-found: error

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: gver
      
