name: Go

on:  
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test
      run: go test -v ./...

    - name: Run
      run: go run -v ./...
